### ISSUE TITLE
Documentation for collaboration refers to `COLLABORATION_APP_WOPISRC` instead of `COLLABORATION_WOPI_SRC`

### ISSUE THREAD

**Issue by DionTimmermann** [owncloud/docs-ocis#1013]
The collaboration documentation states that `COLLABORATION_APP_WOPISRC` must be set to the URL of the WOPI server, but the example at the bottom of the page indicates that the parameter is actually called `COLLABORATION_WOPI_SRC`.

https://github.com/owncloud/docs-ocis/blob/cc133f2a488cab52720aee459ff0e45e1e2a0ccb/modules/ROOT/pages/deployment/services/s-list/collaboration.adoc?plain=1#L51-L53

**Comment by mmattel** [comment]
@DionTimmermann great catch, thanks for highlighting 👍
