### ISSUE TITLE
backup and restore

### ISSUE THREAD

**Issue by wkloucek** [owncloud/docs-ocis#208]
## Is your feature request related to a problem? Please describe.
As an admin I want to have a documentation and well understood and safe  mechanism to backup and restore supported storage

## Describe the solution you'd like
How can I backup the storage (eg. rsync, rclone, snapshots)
Do I need to verify something (eg. extended attributes are not lost)
What order and which steps need to be performed (eg. take oCIS offline, snapshot disk, snapshot S3 bucket, take oCIS online)

## Describe alternatives you've considered
No backup is no option.

## Additional context
Highly dependent on storage backend

**Comment by Tomaszal** [comment]
Perhaps some basic directions could be written on this issue seeing how there is no documentation for this yet? At least for the base [owncloud/ocis](https://hub.docker.com/r/owncloud/ocis) image, knowing which files/folders should be backed up from `/var/lib/ocis` and `/etc/ocis` would already be really helpful. Also knowing if any "dumps" would need to be created (f.e. as is the case with databases).

I'm not familiar with the architecture of OCIS, but it seems to be quite complex. So answering those questions myself would be quite challenging. Hopefully someone here can help, as this is the only, but very critical thing preventing me from using OCIS in production.
