### ISSUE TITLE
Document supported client versions

### ISSUE THREAD

**Issue by pmaier1** [owncloud/docs-ocis#209]
## Where
https://doc.owncloud.com/ocis/next/prerequisites/prerequisites.html

## What
- Supported versions of iOS
- Supported versions of Android
- Supported versions of Desktop

TBD

**Comment by mmattel** [comment]
Prerequisites is about ocis itself.
Will do an own client page where we also document limitations if any, that will also contain links to the client doc (per client) for further reading.

Atm I have no clear knowledge/statement which client release do already support which ocis functionality - input needed.

**Comment by michaelstingl** [comment]
Recent Desktop, Android & iOS apps work with oCIS. oCIS Spaces will require the upcoming 3.0 version of the Desktop app, and the upcoming 12.0 version of the iOS app. Both available as public pre-releases. No ETA for Android yet.

**Comment by mmattel** [comment]
Thanks @michaelstingl 
Maybe a stupid question, but in ocis, all is about spaces. Taking the current client versions not being capable of spaces, what will they see or not see? Means, where is the limitation?

@tbsbdr @micbar open for your input too

**Comment by michaelstingl** [comment]
> Taking the current client versions not being capable of spaces, what will they see or not see?

oCIS exposes the user account fully backwards compatible via the WebDAV endpoints. Users will see their personal files and received shares the same way as in oC10.

**Comment by EParzefall** [comment]
@michaelstingl Android version will be called 3.0, a major version jump like with iOS and desktop?
Where can the pre-releases be found?

**Comment by michaelstingl** [comment]
> @michaelstingl Android version will be called 3.0, a major version jump like with iOS and desktop?

Yes, contains all the "new architecture" magic.

Entry point:
- https://github.com/owncloud/android/issues/2351)

> Where can the pre-releases be found?

Will be published here:
https://owncloud.com/beta-testing/#android

You can follow the progress here:
- https://github.com/owncloud/android/issues/3724
- https://github.com/owncloud/android/issues/3743

**Comment by EParzefall** [comment]
@michaelstingl Thanks! The iOS and Desktop app pre-releases are also only available on github, no ready-to-install versions?

**Comment by michaelstingl** [comment]
> @michaelstingl Thanks! The iOS and Desktop app pre-releases are also only available on github, no ready-to-install versions?

iOS 12.0 pre-release builds already available in our public TestFlight beta:
https://owncloud.com/beta-testing/#ios

Desktop 3.0 pre-release builds available here, and can be easily installed:
https://github.com/owncloud/client/releases?q=v3.&expanded=true

We should link them in https://owncloud.com/beta-testing too…

**Comment by mmattel** [comment]
Closed as completed via #243 and #263
