### ISSUE TITLE
Document new command line for listing and cleaning up expired uploads

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ocis#211]
References: https://github.com/owncloud/ocis/pull/4256 (Add a cli for listing and cleaning up expired uploads)

@aduffeck can you pls add some comments regarding
* arguments/options*
* output etc 
* when this command is used
* what triggers an admin to run it

**Comment by aduffeck** [comment]
Some more context as a preparation for the documentation:

The referenced PR adds a new `uploads` sub-command to `ocis storage-users` which itself has two sub-commands `uploads list` and `uploads purge`. Neither of them takes arguments, they just use the config in the same way `ocis storage-users` does and lists unfinished uploads on disk or cleans them up when they expired.
Expiry can be defined using the `upload_expiration`/`STORAGE_USERS_UPLOAD_EXPIRATION` configuration option.

In practice it looks like this:

```
$ ocis storage-users uploads list
Incomplete uploads:
 - e5b43157-adb2-42e8-8e89-a6e7dc7553e7 (1024MB, Size: 1073741824, Expires: 2022-06-20T00:56:05+02:00)

$ ocis storage-users uploads purge
Purging e5b43157-adb2-42e8-8e89-a6e7dc7553e7 (Filename: 1024MB, Size: 1073741824, Expires: 2022-06-20T00:56:05+02:00)
```

Please let me know if you need more information.

**Comment by mmattel** [comment]
Referencing: https://github.com/owncloud/ocis/pull/4403 (restructure storage-users upload command)
