### ISSUE TITLE
Docs. Docker-compose section. nonexistent link

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/docs-ocis#297]
in section https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#docker-compose we have nonexistent link [ocis individual services](https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_individual_services)

cc @mmattel

**Comment by mmattel** [comment]
**Caused by:**

<img src="https://user-images.githubusercontent.com/3321281/201140288-8a5470f5-b1fb-455b-a0ac-a024b7328ee0.png" width="400">

Needs rewriting the text in the documentation to remove the link properly
