### ISSUE TITLE
document service limits (HA / scalability)

### ISSUE THREAD

**Issue by wkloucek** [owncloud/docs-ocis#300]
- search can not be started multiple times (and there is no plugin replacement), so use in HA / scaled installations is limited.

- idm cannot be started multiple times. Should not be used in HA / scaled installations, but instead replaced by an LDAP server that supports HA / scaling. Even if no HA / scaling is needed, the IDM is only supported up to ~200 (??) users.

- idp cannot be started multiple times. Should not be used in HA / scaled installations, but instead replaced by an OIDC provider server that supports HA / scaling. It has a bare minimum feature set (eg. you cannot easily revoke single sessions)

- store cannot be started multiple times. We are still looking into removing or making the store scale, see https://github.com/owncloud/ocis/issues/3913

- nats cannot be started multiple times. Should not be used in HA / scaled installations, but instead replaced by an NATS installation that is HA / scaled.

see also https://github.com/owncloud/ocis-charts/issues/77#issuecomment-1293134539

**Comment by mmattel** [comment]
What about creating a "Deployment Limitation" page describing the above issues?

> instead replaced by an NATS installation that is HA / scaled.

need more details on that and what is meant.
