### ISSUE TITLE
Docs for third-party OIDC settings, including credentials

### ISSUE THREAD

**Issue by taliaferro** [owncloud/docs-ocis#304]
The OCIS docs mention that I can use an external OpenID Connect provider like Keycloak, and some of the settings for that are in the Helm section, in the example `values.yml`. 

One question the docs don't answer, however, is _where do I put my OIDC client credentials?_ There's no reference to any Kubernetes secret to contain the client ID/secret, nor any environment variables to set or config files to populate. Without those credentials, requests from OCIS will be rejected by my IdP.

**Comment by mmattel** [comment]
@wkloucek can you help?

**Comment by taliaferro** [comment]
Oh, I understand -- I guess if the client ID is static, and already documented in the conventional Server docs, then this issue may not be relevant

**Comment by taliaferro** [comment]
But the Web client ID is supposed to be in `config.php` -- there's no PHP in OCIS; do I specify the client ID in a secret?
That Keycloak config file makes it look like the client ID is just "web".

**Comment by taliaferro** [comment]
Oh -- I take it back...looking at the logs from my IdP, it looks like the client ID  really is just `web`.
