### ISSUE TITLE
Generic Config link broken

### ISSUE THREAD

**Issue by pandalec** [owncloud/docs-ocis#318]
Hey! 

I am currently trying to install ocis via helm but I can't find the `generic-config.yaml`. The file is mentioned here:
https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#define-generic-configs
Is the link broken?

**Comment by mmattel** [comment]
Many thanks for reporting this, fixed with #319
Sorry for any inconvinience caused
