### ISSUE TITLE
Document how to add the full text search to ocis

### ISSUE THREAD

**Issue by micbar** [owncloud/docs-ocis#347]
# Description

The infinite Scale single binary includes a "ready-to-use" search service. This indexes the all files  metadata in ocis (file names. folder names, tags)

The search service can also index file content when admins add a third party dependency for the content parsig.

## Scope

Deployment example: ocis wopi

Relevant Lines 

- https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml#L218-L222
- https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml#L76-L77

- [ ] Document what the default features of the search service are (metadata indexing)
- [ ] Document what needs to be done do add content indexing
  - [ ] Add Apache tika as a extra container (https://tika.apache.org/)
  - [ ] Explain how to configure the ocis search service to use tika
  - [ ] Short notice about how this increases the index size
  - [ ] Explain how and when to use the re-index command
  - [ ] Impacts and handling of a growing index size

## Missing artifacts

- [x] Needs Readme.md for the search service

**Comment by mmattel** [comment]
References: https://github.com/owncloud/ocis/issues/5481 (Search Service - wopi - docker compose - TIKA URL)

**Comment by mmattel** [comment]
need to reopen as #366 was only a part of the game

**Comment by mmattel** [comment]
Fust for further reading:
[Index considerations](https://www.ibm.com/docs/en/cmofz/10.5.0?topic=fts-index-considerations)
[Estimating the size of the FTS index](https://docs.bmc.com/docs/ars2105/estimating-the-size-of-the-fts-index-1002222447.html)
