### ISSUE TITLE
Wrong frontend.yaml filename

### ISSUE THREAD

**Issue by verymilan** [owncloud/docs-ocis#379]
The documentation points to `frontend-config-example.yaml` which would be interpreted as `frontend-config.yaml`, but it actually has to be `frontend.yaml`. Not sure where this is generated, otherwise i would have made a pullrequest.

**Comment by mmattel** [comment]
We pull generated content from the ocis repo which is the reason for the naming. This makes it easier to identify things. You will see this scheme in all services. The important thing is, that, despite any naming of the source, the content is shown correctly from the file referenced. If there is an issue contentwise, let us know. Else things are correct.
Note, the yaml file is an example file and only c/p things is never a good idea. You have to rename it for proper use (see the config rules) makes people at least think about what to do when. There is additional documentation containing working examples.

Anyways, thanks for filing the issue 👍

**Comment by verymilan** [comment]
Interesting, did not notice but yes, -config-example appears to be common in the docs. I am aware that these are examples and need to be renamed. Thats normal for almost everything for selfhosting. However what's not normal is that you also need to substract a `-config`. That's confusing and i am sure i won't be the last one running into this trap. And thats why i have opened this issue.
