### ISSUE TITLE
Broken link to spaces dev guide

### ISSUE THREAD

**Issue by philippgille** [owncloud/docs-ocis#384]
Hello :wave: ,

In the _Spaces_ section of the architecture docs page: <https://doc.owncloud.com/ocis/next/architecture/architecture.html#spaces>

There's a link to <https://owncloud.dev/extensions/storage/spaces/>.

That page leads to a 404 Not Found error though.

I assume this one is the correct one? <https://owncloud.dev/ocis/storage/spaces/>

**Comment by mmattel** [comment]
Thanks for catching, will fix tomorrow

**Comment by philippgille** [comment]
Thanks for the fix! :bow:
