### ISSUE TITLE
Link to demo users

### ISSUE THREAD

**Issue by philippgille** [owncloud/docs-ocis#385]
Hello :wave: ,

After landing on <https://github.com/owncloud/ocis>, I followed the link to <https://doc.owncloud.com/ocis/next>, and checked the quick start guide: <https://doc.owncloud.com/ocis/next/quickguide/quickguide.html>

Some admin credentials are printed, but I saw there were other demo users ("Einstein" etc), which I wanted to try, but I didn't find info about their credentials.

Searching for info about the demo users, I found that the bad discoverability has been filed as issue in the past: <https://github.com/owncloud/ocis/issues/1782>

But its fix only adds documentation about demo users on https://owncloud.dev/ocis/getting-started/demo-users/, which is ~not linked or otherwise available on <https://doc.owncloud.com/ocis/next>~ not easily to find.

I would propose to add a link to the demo user doc page at the bottom of the quickguide page.

**Comment by philippgille** [comment]
Ah, I found the demo user info on the owncloud.com docs page now: <https://doc.owncloud.com/ocis/next/deployment/general/general-info.html#demo-users-and-groups>

Then I guess _that_ page can be linked on the bottom of the quickguide page.

**Comment by mmattel** [comment]
@philippgille thanks for filing the issue.

We have at the main intro page containing a text when you want to go for a deployment.
We have in the intro of the deployment a section for important things to read which included the general info page you already found.
This possibly frustrates you, but next request would be another thing to link in the quickguide page - which finally end up not longer be a quickguide page...
What we are working on is improving search, but this takes a bit until implemented.

The ocis repo and the dev page are intended for developers, except if content is exclicit mentioned in the ocis admin docs. The issue you referenced was created long time before the ocis admin documentation existed and is obsolete now.

I hope that the ocis admin documentation can give you as much info as required. It is growing daily and we are putting much afford in. Feel free to file issues if you find things that need a correction or rewrite. You can also ask questions on [central](https://central.owncloud.org).
