### ISSUE TITLE
Docker Compose vs docker-compose

### ISSUE THREAD

**Issue by cyberdork33** [owncloud/docs-ocis#386]
In [this section](https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#docker-compose) of the documentation, it appears that the docker compose plugin and docker-compose executable are being convoluted. Running 'which docker-compose' would provide no output and 'sudo apt-cache policy docker-compose' would indicate it is not installed even when the docker compose plugin _is_ installed on systems such as Debian Bullseye. Further down, it is indicated that the new 2.X (go-based) (which is the docker compose plugin versus the standalone executable) is preferred. 

docker-compose:
* invoked with the command 'docker-compose'
* standalone executable
* represented by the 'docker-compose' package in Debian.
* older v1.x python code

docker compose:
* invoked with the command 'docker compose'
* is a sub-command of the docker executable
* represented by the 'docker-compose-plugin' package in Debian
* newer v2.x go code.

Please update the documentation to differentiate between the docker-compose standalone executable and the docker compose plugin. Please update test to use the docker compose plugin syntax if that is the preferred application.

Reference:
https://docs.docker.com/compose/compose-v2/#differences-between-compose-v1-and-compose-v2

**Comment by mmattel** [comment]
@cyberdork33 you are right, I will fix. Thanks for highlighting 👍

**Comment by cyberdork33** [comment]
Thanks. It is likely that people using docker compose regularly already understand this, but I could see how it might be quite misleading to someone not so familiar.

**Comment by EParzefall** [comment]
@phil-davis Is the docker compose plugin (go) part of the tests or only docker-compose?

**Comment by phil-davis** [comment]
> @phil-davis Is the docker compose plugin (go) part of the tests or only docker-compose?

AFAIK the test pipelines start each of the services as individual docker images, and do not use "docker compose" at all.
