### ISSUE TITLE
[QA] Bare metal docs with apache does not work

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-ocis#503]
We explain how to setup apache as a reverse proxy in
https://github.com/owncloud/docs-ocis/blob/master/modules/ROOT/pages/depl-examples/bare-metal.adoc

This fails.
* Installation instructins are missing. I have found that we need at least `apt install apache2 certbot python3-certbot-apache`

* `May 17 11:20:49 jw-ocis-daily-3k7 apachectl[11539]: apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 31 of /etc/apache2/sites-enabled/ocis.conf: Could not open configuration file /etc/letsencrypt/options-ssl-apache.conf: No such file or directory`
   - this file is not installed when following the docs, and not with `apt install apache2 certbot python3-certbot-apache`
* `May 17 11:31:12 jw-ocis-daily-3k7 apachectl[11772]: Invalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration`
  - Needs `a2enmod proxy` ?
* `May 17 11:38:49 jw-ocis-daily-3k7 apachectl[11824]: SSLCertificateFile: file '/etc/letsencrypt/live/ocis.example.com/fullchain.pem' does not exist or is empty`
  - the entire folder /etc/letsencrypt/live is missing
  - we probably have a chicken-and-egg problem: certbot does not run without apache, and apache does not start, with all the missing certbot things...

**Comment by mmattel** [comment]
The documentation clearly says:

* In the [Introduction](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html#introduction):
...Note that this guide expects that prerequisite of a computer with an installed Linux distribution of choice is met and required software other than Infinite Scale is installed and preconfigured. There is no detailed explanation but, where possible, links for more information are provided.

* And that [Requirements](https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html#requirements) need to be met. Which includes a link to certbot. As there are many ways and different distributions, one takes the preferred installation method for his environment which we DO NOT covere here as that would explode the docs unnecessarily.
