### ISSUE TITLE
Document migration from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by micbar** [owncloud/docs-ocis#516]
# Description

## Steps

1. Shut down ocis
2. Update ocis (docker pull or binary)
3. Add the Graph Application ID to the config
  - Either editing the `ocis.yaml` by adding `application -> id`  under the graph key (recommended)
  - OR setting `GRAPH_APPLICATION_ID` as ENV variable 
4. Delete the full search index (`rm -rf <ocis-data-path>/search/*`) 
5. Start ocis again
6. During the restart of ocis the metadata store in the DecomposedFS will be migrated to `messagepack`. You will see some  related log messages. If you want to prevent the migration, set `OCIS_DECOMPOSEDFS_METADATA_BACKEND=xattrs`. The `xattrs` backend is considered deprecated and will be removed soon.
7. The empty search index will be recreated space by space when something changes in a space. You can also use the ocis cli to re-index all spaces. (@mmattel I think we have a link for that) 

### Example part of ocis.yaml

```yaml
graph:
  application:
    id: ac641fbb-f54b-44d9-993a-6aaf123983f9
...
 ```

**Comment by mmattel** [comment]
References: https://github.com/owncloud/ocis/pull/6458 ([docs-only] GRAPH_APPLICATION_ID envvar text fix)

**Comment by mmattel** [comment]
@micbar when upgrading from 2 to 3, manually setting `GRAPH_APPLICATION_ID` is ok.
But what to do when you have a fresh installation?
