### ISSUE TITLE
Change the command for running the ocis in detached mode in case of ZSH shell for binary setup

### ISSUE THREAD

**Issue by KarunAtreya** [owncloud/docs-ocis#570]
## WHAT Needs to be Documented?
command for running ocis server in detached mode in Zsh shell should be:
```
ocis server & disown %%
```
## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html#recurring-start-of-infinite-scale

## WHY Should This Change Be Made?
while using the command in the documentation in the above link which is:
```
ocis server & disown $!
```
which gives the error as:
![disownInZsh](https://github.com/owncloud/docs-ocis/assets/33852651/449faa14-a950-4c2c-934a-3ac64d515b40)
 because the `disown` in zsh takes `job id` not the `process id` and `$!` gives `process id` so it doesnot works
and also the system logouts if the shell is terminated.
`%%` gives the `current job id` so it should be used instead of $!

using:
```
ocis server & disown %%
```
gives 
![Screenshot from 2023-07-21 12-17-20](https://github.com/owncloud/docs-ocis/assets/33852651/5b4e7707-3fa9-4c75-8888-5b19acd47daf)
and server runs on background when the shell is terminated.

**Comment by mmattel** [comment]
@KarunAtreya thanks for catching this 👍 fix is here: #571
