### ISSUE TITLE
more info of env variables required while setting up systemd for ocis in binary setup documentation page

### ISSUE THREAD

**Issue by KarunAtreya** [owncloud/docs-ocis#573]
## WHAT Needs to be Documented?
In the documentation of setting up systemd for ocis binary setup.
the example with a minimal set of environment variables in  ``` /etc/ocis/ocis.env ``` used should be 
```
OCIS_INSECURE=true
OCIS_URL=https://localhost:9200
PROXY_HTTP_ADDR=0.0.0.0:9200
OCIS_LOG_LEVEL=error
OCIS_CONFIG_DIR=/etc/ocis/
OCIS_BASE_DATA_PATH=/etc/ocis/
```
and also information on initialization should be added as:
```
 sudo -u ocis ocis init --config-path /etc/ocis/
```
## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html#create-a-service-user

## WHY Should This Change Be Made?
Since the default path for config files for binary setup is ```$HOME/.ocis/config/``` daemon cannot start because 
system looks in ```/home/ocis/.ocis/config``` but our created system user ocis does not have home directory as we create the user with system and create no home option
the same problem arises for base data path too (default path is ```$HOME/.ocis/ ```)
So, these too variables should be added on ocis.env
OCIS_CONFIG_DIR=/etc/ocis/
OCIS_BASE_DATA_PATH=/etc/ocis/
NOTE: though some information about default path are available in general information (https://doc.owncloud.com/ocis/next/deployment/general/general-info.html) it would be easy for user if these information are in this page. 

and  for initializaing the ocis while setting up systemd should also be added because while initializing normally with only ``ocis init`` will try to create the ``ocis.yaml`` file on the default path ```$HOME/.ocis/```. 
 ```sudo -u ocis ocis init --config-path /etc/ocis/```  initializes the ocis.yaml in the given directory and by the user ocis

**Comment by KarunAtreya** [comment]
this is the screen shot before setting config path:
![Screenshot from 2023-07-24 12-35-53](https://github.com/owncloud/docs-ocis/assets/33852651/31da8f47-b34e-43d3-a13f-5595459f28c5)
this is the screen shot after setting config path:
![Screenshot from 2023-07-24 12-45-10](https://github.com/owncloud/docs-ocis/assets/33852651/d49d9f6e-9f95-48ed-9137-03082289c5ef)
this is the screenshot after setting both config and base data path:
![Screenshot from 2023-07-24 12-46-26](https://github.com/owncloud/docs-ocis/assets/33852651/7a89b985-1223-450a-a611-6e2e93b44afa)

**Comment by mmattel** [comment]
I am wondering about your findings as we have clearly described and used the settings accordingly, see: https://doc.owncloud.com/ocis/next/depl-examples/bare-metal.html#used-settings

Can you explain in more depth?

**Comment by KarunAtreya** [comment]
@mmattel My findings are same as the link you have mentioed above.
Only catch is that the deployment of systemd in the `binary setup page` (https://doc.owncloud.com/ocis/next/deployment/binary/binary-setup.html#setting-up-systemd-for-infinite-scale) is bit different from the deployment example in the link you provided. There is less information about initialization and setting env variables for config path and data path. So i think this should be added on the page as well in the `setting up systemd for infinite scale` section of `binary setup page`.
