### ISSUE TITLE
New command: ocis migrate rebuild-jsoncs3-indexes

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ocis#585]
References: https://github.com/owncloud/ocis/pull/6971 (Rebuild jsoncs3 index)

```
ocis migrate rebuild-jsoncs3-indexes
Scanning storage storage-users-1 (1/1)
  Rebuilding space 1/1...  done
done
```

To be added at:
* [Maintenance Commands](https://doc.owncloud.com/ocis/next/maintenance/commands/commands.html)

* and as part of the migration step at: [Upgrade Steps](https://doc.owncloud.com/ocis/next/migration/upgrading-ocis.html#upgrade-steps)

**Comment by aduffeck** [comment]
@mmattel First try at the description as you asked for:

```
Previous versions of ocis (< 3.1.0) sometimes lost shares from the "Shared with others" and "Shared with me" lists under certain conditions. The new `ocis migrate rebuild-jsoncs3-indexes` can be used to rebuild those lists.
```
