### ISSUE TITLE
[Create HowTo] Getting Started: Setting Up Infinite Scale as your Private Cloud on uberspace

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#588]
### Steps to reproduce
1. read https://owncloud.com/de/news/hosting-infinite-scale-uberspace-ubernauten
2. unclear if the HowTo is still valid

### Expected behaviour
- Howto should be available in the doku
- Howto should be up-to-date
- Add: How can I upgrade to a newer ocis versions

### Actual behaviour
- unclear to the user if the howto is up-to-date
- bad readability of commandline instructions

### Background
- I'd like to give a webinar on the topic (audience will be home/family admins)
- webinar will be recorded and published on youtube
- The HowTo  must be linked in the video description and must be provided for the webinar "All commands and steps can be found [here]" 
- User: 1-30 user
- link to conditions (pricing, storage, access)

**Comment by michaelstingl** [comment]
> * Howto should be available in the doku

Tutorial, independent from the product docs. Sounds more like Knowledge Base…
- https://doc.owncloud.com/ocis/next/additional-information/knowledge-base.html

Alternative would be:
- https://github.com/owncloud/ocis/issues/6568

**Comment by mmattel** [comment]
This has been implemented via https://github.com/owncloud/ocis/pull/7910 ([docs-only] Adding Ubernauten Deployment Howto) into the dev-docs.
