### ISSUE TITLE
Avoid a very common pitfall with PROXY_HTTP_ADDR

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ocis#623]
References: https://github.com/owncloud/ocis/issues/6441 (Failing to create new user)

This is a very common pitfall.

`PROXY_HTTP_ADDR=localhost:9200` is not correct.

Let me explain:

- The default value is `PROXY_HTTP_ADDR=127.0.0.0:9200` which causes ocis to **only bind to the local network interface**
- In your case you should use `PROXY_HTTP_ADDR=0.0.0.0:9200` to tell ocis that you want to **bind it to all network interfaces** because you are not accessing it via localhost

**Comment by jameskimmel** [comment]
This seems to be changed already?
