### ISSUE TITLE
Update thumbnail description, add query parameters

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ocis#671]
References: https://github.com/owncloud/ocis/pull/7853 ([docs-only] Adding thumbnail query parameters to thumbnail)

**Comment by michaelstingl** [comment]
https://github.com/owncloud/ocis/pull/7853 is for developers, not for admins. Covering on owncloud.dev is sufficient.

/cc @tbsbdr @micbar

**Comment by micbar** [comment]
agreed @michaelstingl

**Comment by mmattel** [comment]
@michaelstingl @micbar For the next time, only comment but dont close the issue because I take a closer look which things need to be changed. As you can see, I had to remove some existing content in the thumbnail description here to correct it.
