### ISSUE TITLE
Evaluate Easy Entry Docs

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#775]
Evaluation of the first milestone (https://github.com/owncloud/docs-ocis/milestone/1 )

### Evaluation
The success of the initiative will be evaluated via a remote usability test with 3 persons:

### 🙍‍♀️ Persona skills:

- bash basics (ssh, actions on files, edit files nano/vi)
- knows what to google in order to set up a lets encrypt certificate
- knows what to google in order to set up a database in mysql
- has heard about docker and docker compose and is interested in using it the first time 

### Task

Setup Infinite Scale on the internet so that you can share fotos with your family.

 

The test will be video-recorded.

**Comment by mmattel** [comment]
Closing via #884 and 891
