### ISSUE TITLE
Add Teaser Image for Ubuntu+Docker HowTo

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#803]
# Description

## User Stories

* > As a user I want to see within 1.000 milliseconds if I'm on the right page so that I can stay here.

## Value
- redice churn rate

## Acceptance Criteria
- add a teaser image

![Image](https://github.com/owncloud/docs-ocis/assets/26610733/c304b2af-b76e-4b14-a691-5a007fb99288)

**Comment by tbsbdr** [comment]
@mmattel I suggest the above as the teaserimage. could you please embedd it "[above the fold](https://en.wikipedia.org/wiki/Above_the_fold)"

**Comment by mmattel** [comment]
Hmmm, just thinking, logo of ownCloud or Infinite Scale ?

**Comment by mmattel** [comment]
Added, we can change at any time.
