### ISSUE TITLE
How-To must be easily found and clicked via search engine

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#807]
# Description

## User Stories

* > As a user who is googling for "owncloud docker install" I want a helpful, reliable site on top of my search so that I can navigate quickly to the howto.

## Value

- visibility

## Acceptance Criteria

- SEO-orientated Title
- Title that makes you klick
- Proposal: **Install ownCloud via Docker on Ubuntu**

## Visual

For a better impression: The snippet could look like this - at least the headline

![Image](https://github.com/owncloud/docs-ocis/assets/26610733/e9553407-3055-4595-8840-94a350f0d38d)

**Comment by mmattel** [comment]
**Install ownCloud via Docker on Ubuntu** --> added, we can change at any time.
