### ISSUE TITLE
Example how to deploy on hetzner

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#838]
# Description
## prerequisite
- test access to hetzner

## User Stories

* > As a user who wants to host ocis on hetzner, I want a guide howto setup ocis on hetzner.

## Value
- spread ocis

## Acceptance Criteria
- describe an example on minimal requirements of the server that needs to be rented
  - OS image, eg. 22.04 (ideally 24.04 if possible)
  - shared CPU
  - Architecture: x86 for highest compatibility (?)
  - ram: cheapest possible option
  - IPv6 is sufficient
  - SSH Key: optional
  - Volume: neccesary? if yes, eg. 10 GB
  - Firewall (?)
  - Backup (?)
  - Platzierungsgruppe: no
  - Label: no
  - Cloud init: no (but should be made possible via another story)
  - Domain: default ugly domain that comes with the basic server

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by mmattel** [comment]
Closing via #891
